# Generated by Django 5.1.3 on 2024-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_contact_number', models.CharField(max_length=15)),
                ('patient_email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('purpose_of_visit', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('appointment_status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receptionistprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='NurseProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
    ]
