# Generated by Django 5.1.3 on 2024-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment_remove_doctorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='Unknown Doctor', max_length=100),
        ),
    ]
