# Generated by Django 5.1.3 on 2024-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('opd', 'Outpatient Department (OPD)'), ('ipd', 'Inpatient Department (IPD)'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry & Mental Health'), ('ophthalmology', 'Ophthalmology'), ('pharmacy', 'Pharmacy'), ('orthopedics', 'Orthopedics'), ('nephrology', 'Nephrology'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('infectious_diseases', 'Infectious Diseases')], default='general', max_length=50),
        ),
    ]
