# Generated by Django 5.1.3 on 2024-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('opd', 'Outpatient Department (OPD)'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry & Mental Health'), ('ophthalmology', 'Ophthalmology'), ('pharmacy', 'Pharmacy'), ('orthopedics', 'Orthopedics'), ('nephrology', 'Nephrology'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('infectious_diseases', 'Infectious Diseases')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='DEPARTMENT',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('opd', 'Outpatient Department (OPD)'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry & Mental Health'), ('ophthalmology', 'Ophthalmology'), ('pharmacy', 'Pharmacy'), ('orthopedics', 'Orthopedics'), ('nephrology', 'Nephrology'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('infectious_diseases', 'Infectious Diseases')], default='general', max_length=100),
        ),
    ]
