# Generated by Django 5.1.3 on 2024-12-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
    ]
