# Generated by Django 5.1.3 on 2024-12-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treatment',
        ),
    ]
