# Generated by Django 5.1.3 on 2024-12-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_customuser_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dr_name',
        ),
    ]
