# Generated by Django 5.1.3 on 2024-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_customuser_dr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
