# Generated by Django 5.1.3 on 2024-12-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
