# Generated by Django 5.1.3 on 2024-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_rename_amount_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitdischargedetails',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitdischargedetails',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
