# Generated by Django 5.1.3 on 2024-12-09 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_admitdischargedetails_treatment_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('admit_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consultancy_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
