# Generated by Django 5.1.3 on 2024-12-10 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='admit_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='discharge_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
