# Generated by Django 5.1.3 on 2024-12-10 19:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_admitdischargedetails_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='admit_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Admit Date'),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discharge Date'),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='discharge_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Discharge Summary'),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Treatment Plan'),
        ),
        migrations.AlterField(
            model_name='admitdischargedetails',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward'),
        ),
    ]
