# Generated by Django 5.1.3 on 2024-12-11 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_admitdischargedetails_admit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitdischargedetails',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AdmitDischargeDetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
